Update to Lucky v0.18.4

diff --git a/script/setup b/script/setup
--- a/script/setup
+++ b/script/setup
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
 # Exit if any subcommand fails
 set -e
@@ -8,6 +8,18 @@ indent() {
   while read LINE; do
     echo "  $LINE" || true
   done
+}
+
+# Ensure postgres client tools are installed
+check_postgres() {
+  if ! command -v createdb > /dev/null; then
+    printf 'Please install the postgres CLI tools, then try again.\n'
+    if [[ "$OSTYPE" == "darwin"* ]]; then
+      printf "If you're using Postgres.app, see https://postgresapp.com/documentation/cli-tools.html.\n"
+    fi
+    printf 'See https://www.postgresql.org/docs/current/tutorial-install.html for install instructions.\n'
+    exit 1
+  fi
 }
 
 if ! command -v yarn > /dev/null; then
@@ -32,13 +44,26 @@ if [ -z "$CI" ]; then
 fi
 printf "✔ Done\n" | indent
 
-printf "\n▸ Setting up the database\n"
+if [ ! -f ".env" ]; then
+  printf "\n▸ No .env found. Creating one.\n"
+  touch .env
+  printf "✔ Done\n" | indent
+fi
+
+printf "\n▸ Checking that postgres is installed\n"
+check_postgres | indent
+printf "✔ Done\n" | indent
+
+printf "\n▸ Creating the database\n"
 lucky db.create | indent
+
+printf "\n▸ Verifying postgres connection\n"
+lucky db.verify_connection | indent
 
 printf "\n▸ Migrating the database\n"
 lucky db.migrate | indent
 
-printf "\n▸ Seed the database with required and sample records\n"
+printf "\n▸ Seeding the database with required and sample records\n"
 lucky db.create_required_seeds | indent
 lucky db.create_sample_seeds | indent
 
